import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { ArrowLeft, Github } from "lucide-react";
import { ProjectVisual } from "@/components/portfolio/ProjectVisual";
import { PlaceholderNotice } from "@/components/portfolio/SiteChrome";
import { projects } from "@/data/portfolio";
export const Route = createFileRoute("/projects/$slug")({
  loader:({params})=>{const project=projects.find(p=>p.slug===params.slug);if(!project) throw notFound();return project;},
  head:({loaderData,params})=>{const title=loaderData?`${loaderData.name} case study — Stephen Jarso`:"Project not found — Stephen Jarso";const description=loaderData?.description??"Project case study unavailable.";return {meta:[{title},{name:"description",content:description},{property:"og:title",content:title},{property:"og:description",content:description},{property:"og:type",content:"article"},{property:"og:url",content:`/projects/${params.slug}`},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:`/projects/${params.slug}`}]}}, component:CaseStudy });
function CaseStudy(){const project=Route.useLoaderData();return <main className="page-shell"><Link to="/" className="text-link case-back"><ArrowLeft size={16}/>Back to home</Link><header className="page-intro case-header"><div><p className="eyebrow">{project.number} / {project.category}</p><h1>{project.name}</h1><p className="page-lede">{project.description}</p><ul className="tags">{project.technologies.map(t=><li key={t}>{t}</li>)}</ul></div><ProjectVisual imageSrc={project.imageSrc} imageAlt={project.imageAlt}/></header><div className="case-sections"><Case title="Project overview"><p>{project.overview}</p></Case><Case title="Problem"><p>{project.problem}</p></Case><Case title="Solution"><p>{project.solution}</p></Case><Case title="Architecture"><p>{project.overview}</p></Case><Case title="Technical decisions"><ul>{project.decisions.map(x=><li key={x}>{x}</li>)}</ul></Case><Case title="Challenges"><ul>{project.challenges.map(x=><li key={x}>{x}</li>)}</ul></Case><Case title="What I learned"><p>{project.learned}</p></Case><Case title="Technologies used"><ul className="tags">{project.technologies.map(t=><li key={t}>{t}</li>)}</ul></Case><Case title="Repository & demo"><PlaceholderNotice>Repository and live demo links have not been supplied yet.</PlaceholderNotice><div className="case-links"><span className="button-secondary"><Github size={16}/> GitHub link to add</span></div></Case></div></main>}
function Case({title,children}:{title:string;children:React.ReactNode}){return <section className="case-section"><h2>{title}</h2><div>{children}</div></section>}
